platform :ios,'7.0'
pod 'AFNetworking', '~> 2.6.1'
pod 'SDWebImage'
pod 'MJRefresh', '~> 1.4.7'
pod 'MJExtension'
pod 'UMengSocial'
pod 'MBProgressHUD'
pod 'ZBarSDK'
pod 'SBJson'
pod 'VGParallaxHeader'
pod 'NJKWebViewProgress'
pod 'DZNSegmentedControl'
pod 'IQKeyboardManager', '~> 3.3.7'
pod 'JPush'
pod 'UMengAnalytics-NO-IDFA', '~> 3.6.7'
pod 'MJPhotoBrowser'